export const LOAN_SIM_STEPS = {
  SIMULACION: "SIMULACION",
  EMAIL_VALIDATION: "EMAIL_VALIDATION",
  OTP_VALIDATION: "OTP_VALIDATION",
  COMPLIANCE: "COMPLIANCE",
  CBU_VALIDATION: "CBU_VALIDATION",
  COMPLETADO: "COMPLETADO",
};

export const OTP_CONFIG = {
  OTP_LENGTH: 6,
  COOLDOWN_DURATION: 120, // seconds in frontend
};

export const CBU_CONFIG = {
  CBU_LENGTH: 22,
  CVU_LENGTH: 22,
  CVU_PREFIX: "000",
  CVU_CHECK_DIGIT_POSITION: 7,
  CVU_CHECK_DIGIT_VALUE: "1",
};

export const UI_CONFIG = {
  HOME_URL: "https://www.cofa.com.ar/",
};

export const COOKIE_CONFIG = {
  NAME: "scoringId",
  EXPIRY_DAYS: Date.now() + 2 * 60 * 60 * 1000, // 2 hours
};

export const COMPLIANCE_STEPS = Object.freeze({
  STATUS_CHECK: "STATUS_CHECK",
  INITIAL: "INITIAL",
  TYPE_SELECTION: "TYPE_SELECTION",
  PEP_TYPE_SELECTION: "PEP_TYPE_SELECTION",
  FORM_SO: "FORM_SO",
  FORM_PEP_DIRECT: "FORM_PEP_DIRECT",
  FORM_PEP_INDIRECT: "FORM_PEP_INDIRECT",
});

export const PEP_TIPO = Object.freeze({
  DIRECTO: "DIRECTO",
  INDIRECTO: "INDIRECTO",
});